version: 2.1

executors:
  my-executor: 
    docker: 
      - image: cimg/node:18.4.0 

jobs: 
  build: 
    executor: my-executor
    steps:
      - checkout
      - run: npm run lint  

  test: 
    executor: my-executor 
    steps: 
      - checkout 
      - run: npm run test 

  analyze: 
    executor: my-executor 
    steps: 
      - checkout 
      - run: npm audit 

workflows:
  my-workflows:
    jobs:
      - build 
      - test: 
          requires: 
            - build 
      - analyze: 
          requires: 
            - test 
